### PR TITLE
Changes to allow Noise Sensor readings to be logged

### PR DESCRIPTION
**Pull request by lizdodd**
I have changed uradmon.py index.html.tmpl and skin.conf
I haven't changed the install schema to provide the additional database entries automatically.
This is shared work with evilbunny2008

### CODE REVIEW

**Comment by glennmckechnie** [comment]
This should be a nice addition.  Code looks good.

There's a simple typo for the name Glen. Change it to Glenn in skins/uradmon/index.html.tmpl so that it doesn't propagate further and we should be good to go. I'll then do a Squash and Merge of your changes. 
I'll update the README with "Noise additions by evilbunny2008 and lizdodd". Credit where it's due. :-)

**Comment by evilbunny2008** [comment]
It may be worth pointing out that I've no idea how to migrate to add an additional table/field without dropping existing tables.

**Comment by glennmckechnie** [comment]
I will. 
It's a good thing that it's early days for the skin. There's probably only me with an archive that's large enough to be worth keeping, and that's in sqlite. 
I'll dump the database and play with it later. I'll then bump my uradmon version when I've got the process sussed.

Thanks to you both for the contribution. It is of course, appreciated.

**Comment by lizdodd** [comment]
On Sat, 15 Sep 2018 10:02:28 +0000 (UTC)
evilbunny2008 <notifications@github.com> wrote:

> It may be worth pointing out that I've no idea how to migrate to add
> an additional table/field without dropping existing tables.
> 

I dropped three fields and remade them, to reduce data loss, but as
Glenn noted, it wasn't much data

**Comment by glennmckechnie** [comment]
I've had to bypass the noise field on my installation. It's not available on my unit - which probably explains why it was missing in the first instance. ( I did wonder about the omission :)

Can you check out the dev branch and test it on your machine / s.
uradmon.py and  index.html are the only real changes.  

I'd expect there to be no change on your units. The noise values should continue to be read and stored, and the 4 noise charts continue to be generated.

**Comment by evilbunny2008** [comment]
I'll submit some patches tomorrow to ignore missing data similar to the standard skin ignores missing data supplied from the almanac.

**Comment by glennmckechnie** [comment]
I have made changes already, probably along the same lines as you mention regarding skin.conf and almanac. The critical change is to catch the exception on the missing field.

It's been running overnight without issue here but it needs to be tested against your setups.

Review them at [2edf29f](https://github.com/glennmckechnie/weewx-uradmon/commit/2edf29fc37064231a3771bd4161468d3133b6bd0) and if they look suitable, can you check out the dev branch and test it.

**Comment by evilbunny2008** [comment]
You have #endif in index.html.tmpl, it should be #end if

and you have $mon.noise.has_data should be $month.noise.has_data

**Comment by glennmckechnie** [comment]
Whoops, that was an oversight. Push the actual working version.

[7dbef96](https://github.com/glennmckechnie/weewx-uradmon/commit/7dbef96b1725c8055c4427dfca32a0fe0fb7aae9)

**Comment by evilbunny2008** [comment]
I missed the unoise field, but the rest of the changes work for me.

**Pull request merged**
